/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.orm.view;

import ffos.orm.controller.ObradaZupanije;
import ffos.orm.model.Opcina;
import ffos.orm.model.Zupanija;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FormaZupanija extends javax.swing.JFrame {

    private ObradaZupanije obrada;
    public FormaZupanija() {
        initComponents();
        obrada = new ObradaZupanije();
    }
        private void ucitaj(){
        DefaultListModel<Zupanija> m = new DefaultListModel<>();
        obrada.getZupanije().forEach((z)->{m.addElement(z);});
        lstZupanije.setModel(m);
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivZupanije = new javax.swing.JTextField();
        btnUnesiNazivZupanije = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstZupanije = new javax.swing.JList<>();
        zupPromjeni = new javax.swing.JButton();
        zupObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Unos županije");

        btnUnesiNazivZupanije.setText("Unos zupanije");
        btnUnesiNazivZupanije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNazivZupanijeActionPerformed(evt);
            }
        });

        lstZupanije.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZupanijeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstZupanije);

        zupPromjeni.setText("Promjeni");
        zupPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zupPromjeniActionPerformed(evt);
            }
        });

        zupObrisi.setText("Obriši");
        zupObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zupObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUnesiNazivZupanije)
                            .addComponent(txtNazivZupanije, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zupObrisi)
                            .addComponent(zupPromjeni))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNazivZupanije, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnesiNazivZupanije)
                        .addGap(18, 18, 18)
                        .addComponent(zupPromjeni)
                        .addGap(18, 18, 18)
                        .addComponent(zupObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiNazivZupanijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNazivZupanijeActionPerformed
        Zupanija z = new Zupanija();
        z.setNaziv(txtNazivZupanije.getText());
        obrada.dodajZupanije(z);
        ucitaj();
        
    }//GEN-LAST:event_btnUnesiNazivZupanijeActionPerformed

    private void zupPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zupPromjeniActionPerformed
         try {
            DefaultListModel m = (DefaultListModel)lstZupanije.getModel();
            Zupanija z = (Zupanija)m.get(lstZupanije.getSelectedIndex());
            z.setNaziv(txtNazivZupanije.getText());
            obrada.dodajZupanije(z);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_zupPromjeniActionPerformed

    private void zupObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zupObrisiActionPerformed
        
        try {
            DefaultListModel m = (DefaultListModel)lstZupanije.getModel();
            Zupanija z = (Zupanija)m.get(lstZupanije.getSelectedIndex());
            z.setNaziv(txtNazivZupanije.getText());
            obrada.brisanjeZupanije(z);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }                         
    
    private void listaZupanijaValueChanged(javax.swing.event.ListSelectionEvent evt) {                                         
        try {
            DefaultListModel m = (DefaultListModel)lstZupanije.getModel();
            Zupanija z = (Zupanija)m.get(lstZupanije.getSelectedIndex());
            txtNazivZupanije.setText(z.getNaziv());
        } catch (Exception e) {
        }
    
    
    }//GEN-LAST:event_zupObrisiActionPerformed

    private void lstZupanijeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZupanijeValueChanged
         try {
            DefaultListModel m = (DefaultListModel)lstZupanije.getModel();
            Zupanija z = (Zupanija)m.get(lstZupanije.getSelectedIndex());
            txtNazivZupanije.setText(z.getNaziv());
        } catch (Exception e) {
        }                        

    }//GEN-LAST:event_lstZupanijeValueChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesiNazivZupanije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Zupanija> lstZupanije;
    private javax.swing.JTextField txtNazivZupanije;
    private javax.swing.JButton zupObrisi;
    private javax.swing.JButton zupPromjeni;
    // End of variables declaration//GEN-END:variables
}
